name: Java CI with Gradle

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  build:
    name: Assemble
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install additional tools
        run: sudo apt-get update -qq && sudo apt-get install -y shellcheck procps vim nano net-tools

      - name: Prepare Gradle wrapper
        run: chmod +x gradlew

      - name: Use CI gradle.properties
        run: mv gradle.properties.ci gradle.properties

      - name: Assemble with Gradle
        run: ./gradlew -Pci --console=plain --build-cache assemble

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Prepare Gradle wrapper
        run: chmod +x gradlew

      - name: Use CI gradle.properties
        run: mv gradle.properties.ci gradle.properties

      - name: Run tests with JaCoCo
        run: ./gradlew -Pci --console=plain test jacocoTestReport

      - name: Upload test coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/jacocoHtml/
